### ISSUE TITLE
An AdalServiceException is thrown from line 90 in AccessCaApiController.cs 

### ISSUE THREAD

**Issue by ruimsft** [Azure-Samples/active-directory-dotnet-webapi-onbehalfof-ca#10]
While running the code from .NET native client only, an exception was thrown after MFA passed (asking for the consented dialog). Please check.

![adalserviceexception](https://user-images.githubusercontent.com/10158262/31918665-b5cbea9e-b812-11e7-90ea-3e7cd10840ea.jpg)

**Comment by kalyankrishna1** [comment]
Did you see the notes to allow popups from this app. Please check there are no popups being blocked that are needed by this sample

**Comment by jmprieur** [comment]
You need to press the "Grant access" button for the downstreamapi application
